### ISSUE TITLE
Error: Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by Widdershin** [whitecolor/babel-plugin-cycle-circular#1]
After installing, when attempting to compile with babel I get an `Error: Cannot find module 'minimatch'`.

I see minimatch is imported in your index.js, but it doesn't seem to be present in the package.json?

**Comment by Widdershin** [comment]
This is with babel v6.0.14

**Comment by whitecolor** [comment]
Ah ok I will add as module dep.
